"""
Run this script once on your local machine to extract policy data
from the original HTML file into data/policy-data.js.

Usage: python3 extract-data.py path/to/your/dashboard.html

Output: data/policy-data.js  (loaded via <script> tag, no server needed)
"""
import re, json, sys, os

if len(sys.argv) < 2:
    print("Usage: python3 extract-data.py <path-to-html-file>")
    sys.exit(1)

html_path = sys.argv[1]
out_dir = os.path.join(os.path.dirname(os.path.abspath(html_path)), "data")
out_path = os.path.join(out_dir, "policy-data.js")
os.makedirs(out_dir, exist_ok=True)

with open(html_path, "r", encoding="utf-8") as f:
    html = f.read()

match = re.search(r'<script id="policy-data" type="application/json">(.*?)</script>', html, re.DOTALL)
if not match:
    print("ERROR: Could not find policy data block in HTML file.")
    print("       Expected: <script id=\"policy-data\" type=\"application/json\">")
    sys.exit(1)

data = json.loads(match.group(1).strip())

with open(out_path, "w", encoding="utf-8") as out:
    out.write("// Auto-generated by extract-data.py — do not edit manually\n")
    out.write("const RAW_POLICY_DATA = ")
    json.dump(data, out, indent=2, ensure_ascii=False)
    out.write(";\n")

print(f"Success: wrote {out_path}")
print(f"  Countries: {len(data.get('countries', {}))}")
print(f"  File size: {os.path.getsize(out_path) / 1024:.0f} KB")
